CREATE TABLE IF NOT EXISTS METRICS (
    ID TEXT UNIQUE PRIMARY KEY,
    MTYPE VARCHAR(10) NOT NULL,
    DELTA DECIMAL,
    VALUE DOUBLE PRECISION
);

CREATE UNIQUE INDEX IF NOT EXISTS METRICS_IXID ON METRICS (ID);